version: '3'

services:
  db:
    image: postgres:latest
    container_name: my-db-docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 54321:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
  pg-admin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin-docker
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
       - 4433:443
       - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
  strapi:
    image: suparatpoonsawat/strapi-suparat:1.1.0
    container_name: my-app-docker
    ports:
      - 1337:1337
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_SSL=false
      - DATABASE_CLIENT=postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
  pgadmin_data: